First server implementation
But not working because of:
java.lang.IllegalStateException: spec violation: onNext was signaled from upstream without demand